version: '3.8'

services:
  app:
    build: .
    container_name: lms_gui_app
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: lms_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2004
      MYSQL_DATABASE: lms
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
