# version: "3.9"

services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2004
      MYSQL_DATABASE: lms
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/lms_backup.sql:/docker-entrypoint-initdb.d/lms_backup.sql

volumes:
  db_data:
