version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: lms_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2004
      MYSQL_DATABASE: lms
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/lms_backup.sql:/docker-entrypoint-initdb.d/lms_backup.sql

volumes:
  mysql_data:
